### ISSUE TITLE
Gripper is missing in the URDF file. 

### ISSUE THREAD

**Issue by hassanismail92** [adeguet1/lewansoul-xarm#2]
As mentioned the Gripper is missing in the URDF file, do you have its code? if yes please add it will be helpful for me.

**Comment by adeguet1** [comment]
I don't but I noticed someone forked the repo a while back and based on their comments, it seems they added some support for the gripper.   See fork: https://github.com/Sorokonog/lewansoul-xarm

I hope to review that fork and merge it back but I don't know if and when I'll get some time to do that.

**Comment by hassanismail92** [comment]
Thank you for the Positive response.
I would love if you guide me in the Hardware Interface of the X-Arm. Like which Arduino i used for interconnecting it with my PC?
Also by which command i connect my PC and x-arm what are the Pre-requisites? I would appreciate if you guide me.

**Comment by hassanismail92** [comment]
Also when i launched the command **rosrun lewansoul_xarm xArm-ros.py**   in your fork x-arm
This error came.

**Traceback (most recent call last):
  File "/home/robotics/catkin_ws/src/lewansoul-xarm/scripts/xArm-ros.py", line 42, in <module>
    ros_main()
  File "/home/robotics/catkin_ws/src/lewansoul-xarm/scripts/xArm-ros.py", line 16, in ros_main
    controller = lewansoul_xarm.controller()
  File "/home/robotics/catkin_ws/src/lewansoul-xarm/src/lewansoul_xarm/controller.py", line 59, in __init__
    raise Exception('no device detected, make sure the arm is powered, connected and you have read-write permissions on /dev/hidraw')
Exception: no device detected, make sure the arm is powered, connected and you have read-write permissions on /dev/hidraw
closing xArm controller
Exception AttributeError: "'controller' object has no attribute '_arms'" in <bound method controller.__del__ of <lewansoul_xarm.controller.controller object at 0x7fd672453510>> ignored**

 Is it just because i wasn't connecting Arduino?
