### ISSUE TITLE
My x-arm is not moving.

### ISSUE THREAD

**Issue by hassanismail92** [adeguet1/lewansoul-xarm#3]
My USB is detected by the Ubuntu Linux Machine, When I tried to launch the comman `python` xarm_hardware_interface/scripts/controller.py` inside the xArm_Lewansoul_ROS folder the following error shown.

<easyhid.easyhid.Enumeration object at 0x7f04df105110>
Traceback (most recent call last):
  File "xarm_hardware_interface/scripts/controller.py", line 227, in <module>
    demo()
  File "xarm_hardware_interface/scripts/controller.py", line 188, in demo
    arm = XArm()
  File "xarm_hardware_interface/scripts/controller.py", line 52, in __init__
    assert len(devices) > 0
AssertionError
Closing xArm device
Exception AttributeError: "XArm instance has no attribute 'dev'" in <bound method XArm.__del__ of <__main__.XArm instance at 0x7f04e20197d0>> ignored

What to do now?

**Comment by adeguet1** [comment]
I haven’t tested this code in a while and kind of forgot what the error messages might mean.  I won’t be able to look into this for a few days but meanwhile can you check that your hid raw device is created properly and your permissions are also set correctly based on the instructions in the README?

Anton

---

On Dec 29, 2020, at 7:39 AM, Hassan Ismail <notifications@github.com> wrote:

﻿

My USB is detected by the Ubuntu Linux Machine, When I tried to launch the comman python xarm_hardware_interface/scripts/controller.py` inside the xArm_Lewansoul_ROS folder the following error shown.

<easyhid.easyhid.Enumeration object at 0x7f04df105110>
Traceback (most recent call last):
File "xarm_hardware_interface/scripts/controller.py", line 227, in
demo()
File "xarm_hardware_interface/scripts/controller.py", line 188, in demo
arm = XArm()
File "xarm_hardware_interface/scripts/controller.py", line 52, in init
assert len(devices) > 0
AssertionError
Closing xArm device
Exception AttributeError: "XArm instance has no attribute 'dev'" in <bound method XArm.del of <main.XArm instance at 0x7f04e20197d0>> ignored

What to do now?

**Comment by hassanismail92** [comment]
I think I there is no any need to connect Arduino? I connect X-arm board directly to the USB of my laptop. Is it OK?

**Comment by MAVProxyUser** [comment]
This seems to be a problem due to the use of easyhid. It just flat out doesn't work, even outside this program.
